version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - restore_cache: # special step to restore the dependency cache
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - run:
          name: install-junit-reporter
          command: npm install mocha-junit-reporter # just for CircleCI
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: mkdir coverage
      - run:
          name: npm test
          command: 'npx nyc mocha --reporter mocha-junit-reporter --reporter-options mochaFile=coverage/mocha/test-results.xml'
          when: always
      - store_test_results:
          path: coverage

      - store_artifacts:
          path: ./coverage/mocha/test-results.xml
